site_name: LaTeXTools
pages:
  - "Home": "index.md"
  - "Installation": "install.md"
  - "Features": "features.md"
  - "Keybindings": "keybindings.md"
  - "Completions": "completions.md"
  - "Settings": "settings.md"
  - "Alternative Builders": "alternative-builders.md"
  - "Alternative Viewers": "alternative-viewers.md"
  - "Troubleshooting": "troubleshooting.md"
  - "About": "about.md"
theme: readthedocs
extra_css:
  - extra.css
repo_url: https://github.com/SublimeText/LaTeXTools
